### PR TITLE
Update Jelly template

### PR DESCRIPTION
**Pull request by imuchnik**
This was rendering poorly on newer Jenkins version.

### CODE REVIEW

**Comment by imuchnik** [comment]
Yay OSS and selfies!
[[selfie-placeholder-0]]

**Comment by imuchnik** [comment]
Selfies!!!
selfie-0

**Comment by imuchnik** [comment]
ping @jeffgus @SteveMoyer @abrooke merge merge merge

**Comment by SteveMoyer** [comment]
I don't have perms to merge it

**Comment by AlexTatiyants** [comment]
I can't seem to merge either

**Comment by imuchnik** [comment]
Turns out I could, but usually not very kosher to merge your own prs

**Pull request merged**
